# Generated by Django 3.1.2 on 2020-12-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('heading0', models.CharField(default='', max_length=500)),
                ('heading1', models.CharField(default='', max_length=500)),
                ('heading2', models.CharField(default='', max_length=500)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(upload_to='blog/image')),
            ],
        ),
    ]
