# Generated by Django 3.1.2 on 2020-10-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201021_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='products_desc',
            new_name='product_desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='products_name',
            new_name='product_name',
        ),
    ]
