# Generated by Django 3.1.2 on 2020-11-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201031_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_desc',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_subcategory',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='Subcategory',
        ),
    ]
