# Generated by Django 3.1.2 on 2020-11-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201129_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='msg_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
